server:
  port: 8080

spring:
  application:
    name: KartaLog-Admin
  thymeleaf:
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    de.codecentric: info
