server:
  port: 8083
spring:
  application:
    name: TCGWatcher-Backend
  docker:
    compose:
      enabled: true
      profiles:
        active: local
      file: ${user.dir}/deployment/compose.yml
      lifecycle-management: start_only
      start:
        skip: if_running
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    parameters:
      watcher_readonly.password: ${WATCHER_READONLY_PWD}
      watcher_mig.password: ${WATCHER_MIG_PWD}
      watcher_app.password: ${WATCHER_APP_PWD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
  boot:
    admin:
      client:
        enabled: true
        uri: http://localhost:9090
        instance:
          service-base-url: http://localhost:8083
          management-url: http://localhost:8080/actuator
          management-port: 8081

resilience4j:
  circuitbreaker:
    instances:
      cardMarketCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 10s
        minimum-number-of-calls: 10
        sliding-window-size: 60
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        # ignore-exceptions does not work - seems to be a bug in resilience4j - see io.github.havonte1.tcgwatcher.backend.config.Resilience4jConfig
        # ignore-exceptions:
        #  - jakarta.ws.rs.NotFoundException
  retry:
    instances:
      cardMarketRetry:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - io.github.havonte1.tcgwatcher.backend.adapter.out.webscraper.cardmarket.CloudFlareException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignore-exceptions:
          - jakarta.ws.rs.NotFoundException
management:
  server:
    port: 8084
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,heapdump,threaddump
  endpoint:
    health:
      show-details: always
logging:
  level:
    io.github.havonte1: debug

#playwright:
#  executable-path: /var/lib/snapd/snap/bin/chromium
#playwright:
  #  executable-path: /usr/local/bin/chromium


app:
  data:
    import:
      enabled: true
      sqlite:
        path: import/quicksearch.db

