spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/tcgwatcherdb
    username: watcher_app
    password: ${WATCHER_APP_PWD}
  liquibase:
    enabled: true
    default-schema: watcher
    password: ${WATCHER_MIG_PWD}
    user: watcher_mig
  docker:
    compose:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      show-components: always
  health:
    db:
      enabled: true
      timeout: 10s

playwright:
  executable-path: /usr/bin/chromium

app:
  data:
    import:
      enabled: false
logging:
  level:
    io.github.havonte1: trace
    org.springframework.web: trace
    web: trace
    com.github.tomakehurst: trace
    eu.rekawek: trace
