spring:
  application:
    name: TCGWatcher-Backend
  docker:
    compose:
      enabled: true
      file: ${user.dir}/deployment/compose.yml
      lifecycle-management: start_only
      start:
        skip: if_running
  liquibase:
    parameters:
      watcher_readonly.password: ${WATCHER_READONLY_PWD}
      migration.password: ${MIGRATION_PWD}
      watcher_mig.password: ${WATCHER_MIG_PWD}
      watcher_app.password: ${WATCHER_APP_PWD}
      application.password: ${APPLICATION_PWD}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true

logging:
  level:
    com.github.havonte1: trace
    org.springframework.web: trace
    web: trace

rate-limiter:
  enabled: true
  requestsPerPeriod: 100
  timeoutDurationSec: 60
