server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
spring:
  boot:
    admin:
      client:
        url: http://admin-server:8080
        instance:
          name: TCGWatcher-Backend
          management-url: http://app:8081
          service-base-url: http://app:8080
          auto-registration: true
          auto-deregistration: true
  datasource:
    url: jdbc:postgresql://postgres:5432/tcgwatcherdb
    username: watcher_app
    password: ${WATCHER_APP_PWD}
  liquibase:
    enabled: true
    default-schema: watcher
    password: ${WATCHER_MIG_PWD}
    user: watcher_mig
  docker:
    compose:
      enabled: false
playwright:
  executable-path: /usr/bin/chromium

app:
  data:
    import:
      enabled: false
#logging:
#  level:
#    io.github.havonte1: trace
#    org.springframework.web: trace
#    web: trace
#    com.github.tomakehurst: trace
#    eu.rekawek: trace
