spring:
  application:
    name: TCGWatcher-Backend
  docker:
    compose:
      enabled: true
      file: ${user.dir}/deployment/compose.yml
      lifecycle-management: start_only
      start:
        skip: if_running
  liquibase:
    parameters:
      watcher_readonly.password: ${WATCHER_READONLY_PWD}
      migration.password: ${MIGRATION_PWD}
      watcher_mig.password: ${WATCHER_MIG_PWD}
      watcher_app.password: ${WATCHER_APP_PWD}
      application.password: ${APPLICATION_PWD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
cache:
  ttl-hours: 1
resilience4j:
  circuitbreaker:
    instances:
      cardMarketCircuitBreaker:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 10s
        minimum-number-of-calls: 10
        sliding-window-size: 60
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
        # ignore-exceptions does not work - seems to be a bug in resilience4j - see io.github.havonte1.tcgwatcher.backend.config.Resilience4jConfig
        # ignore-exceptions:
        #  - jakarta.ws.rs.NotFoundException
  retry:
    instances:
      cardMarketRetry:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - io.github.havonte1.tcgwatcher.backend.adapter.out.webscraper.cardmarket.CloudFlareException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
        ignore-exceptions:
          - jakarta.ws.rs.NotFoundException
  ratelimiter:
    instances:
      apiRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 1000
      cardMarketRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 1000
  timelimiter:
    instances:
      cardMarketTimeLimiter:
        timeoutDuration: 2s
        cancelRunningFuture: true
logging:
  level:
    io.github.havonte1: trace
    org.springframework.web: trace
    web: trace
    com.github.tomakehurst: trace
    eu.rekawek: trace
playwright:
  executable-path: /usr/local/bin/chromium
