events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    limit_req_zone $binary_remote_addr zone=external_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=external_conn:10m;

    server {
        listen 80;

        client_max_body_size 1M;
        client_body_buffer_size 128k;

        server_tokens off;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;

        location / {
            if ($args ~* "^.{126,}$") {
                return 414;
            }
            if ($request_uri ~* "^/[^^?]{126,}") {
                return 414;
            }

            limit_req zone=external_limit burst=20 nodelay;
            limit_conn external_conn 20;

            set $backend "app:8080";
            proxy_pass http://$backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}
